import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/app";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Finaliza sua Compra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-appbackground pb-5 overflow-y-auto">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
